# Generated by Django 4.0.4 on 2022-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Cemail', models.CharField(max_length=50)),
                ('Cmessage', models.CharField(max_length=250)),
            ],
        ),
    ]
